# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionPoll', '0004_auto_20160609_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionista',
            name='rating',
            field=models.FloatField(db_index=True, default=1000.0),
        ),
    ]
